CRUDWithRepository/Controllers/WarpingMachineController.cs
using CRUDWithRepository.Core;
using CRUDWithRepository.Infrastructure.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace CRUDWithRepository.UI.Controllers
{
    public class WarpingMachineController : BaseController
    {
        private readonly IWarpingMachineRepository _MachineRepo;

        public WarpingMachineController(IWarpingMachineRepository MachineRepo)
        {
            _MachineRepo = MachineRepo;
        }
        [SessionAuthorize("Admin")]
        public async Task<IActionResult> Index()
        {
            var Machine = await _MachineRepo.GetAll();
            return View(Machine);
        }
        public async Task<IActionResult> CreateOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new WarpingMachine());
            }
            else
            {
                try
                {

                    WarpingMachine Machine = await _MachineRepo.GetById(id);
                    if (Machine != null)
                    {
                        return View(Machine);
                    }
                }
                catch (Exception ex)
                {
                    TempData["successMsg"] = ex.Message;
                    TempData["ReturnCode"] = -1;
                    return View();
                }
                TempData["successMsg"] = $"Warping Machine details not found with Id : {id}";
                TempData["ReturnCode"] = -1;
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(WarpingMachine model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.ID == 0)
                    {
                        model.CreatedDate = DateTime.Now;
                        model.CreatedBy = "Admin";
                        await _MachineRepo.Add(model);
                        TempData["successMsg"] = "Warping Machine created successfully!";
                        TempData["ReturnCode"] = 11;
                        return RedirectToAction("index");
                    }
                    else
                    {
                        model.UpdatedDate = DateTime.Now;
                        model.UpdatedBy = "Admin";
                        await _MachineRepo.Update(model);
                        TempData["successMsg"] = "Warping Machine updated successfully!";
                        TempData["ReturnCode"] = 11;
                        return RedirectToAction("index");
                    }
                }
                else
                {
                    TempData["successMsg"] = "Model state is Invalid ";
                    TempData["ReturnCode"] = -1;
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["successMsg"] = ex.Message;
                TempData["ReturnCode"] = -1;
                return View();
            }

        }
 
    }
}

CRUDWithRepository/Views/WarpingMachine/CreateOrEdit.cshtml
@model CRUDWithRepository.Core.WarpingMachine

@{
    ViewData["Title"] = Model != null && Model.ID == 0 ? "Create Warping Machine" : "Edit Warping Machine";
}

<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4>Warping Machine Master</h4>
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Warping Management System</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Master</a></li>
                    <li class="breadcrumb-item active">Warping Machine Master</li>
                </ol>
            </div>
        </div>

    </div>
    <!-- end page title -->
    @using (Html.BeginForm("CreateOrEdit", "WarpingMachine", FormMethod.Post, new { enctype = "multipart/form-data", @class = "needs-validation", @novalidate = "" }))
{
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                        <h4 class="card-title">Warping Machine Master</h4>
                    <p class="card-title-desc">&nbsp;&nbsp;&nbsp;</p>
                    <form class="needs-validation" novalidate>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="mb-3">
                                 
                                    @Html.HiddenFor(m => m.ID)
                                    @Html.LabelFor(m => m.After, new { @class = "control-label" })
                                        @Html.TextBoxFor(m => m.After, new { @class = "form-control", @maxlength = "200", @required = "required" })
                                        @Html.ValidationMessageFor(m => m.After, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <!-- end col -->
                            <div class="col-md-4">
                                <div class="mb-3">
                                 
                                    @Html.LabelFor(m => m.Before, new { @class = "control-label" })
                                        @Html.TextBoxFor(m => m.Before, new { @class = "form-control", @maxlength = "200" })
                                        @Html.ValidationMessageFor(m => m.Before, "", new { @class = "text-danger" })
                                </div>
                            </div>
                             <div class="col-md-4">
                                <div class="mb-3">
                                 
                                        @Html.LabelFor(m => m.Status, new { @class = "control-label" })
                                        @Html.DropDownListFor(m => m.Status,
                                                 new SelectList(new[] {
                                    new { Value = "1", Text = "Active" },
                                    new { Value = "0", Text = "Inactive" }}, "Value", "Text"), "Select Status", new { @class = "form-control", @required = "required" })
                                   @Html.ValidationMessageFor(m => m.Status, "", new { @class = "text-danger" })

                                </div>
                            </div>
                            
                            <!-- end col -->
                        </div>
                        @if (Model != null && Model.ID == 0)
                        {
                            <button type="submit" class="btn btn-success float-right">
                                Create
                            </button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-success float-right">
                                Update
                            </button>
                        }
                            <a class="btn btn-dark" type="button" href="/WarpingMachine/Index">Cancel</a>
                    </form>
                    <!-- end form -->
                </div>
            </div>
            <!-- end card -->
        </div> <!-- end col -->


    </div>
    }
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CRUDWithRepository/Views/WarpingMachine/Index.cshtml
@model IEnumerable<CRUDWithRepository.Core.WarpingMachine>
@{
    ViewData["Title"] = "Machine List";
}


<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-md-10 col-sm-12">
            <div class="page-title-box">
                <h4>Warping Machine Master</h4>
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">WMS</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Master</a></li>
                    <li class="breadcrumb-item active">Warping Machine Master</li>
                </ol>
            </div>
        </div>
        
        <div class="col-md-2 col-sm-12" style="margin-bottom:10px;">
            <a type="button" href="/WarpingMachine/CreateOrEdit" class="btn btn-info waves-effect waves-light"><i class="ion ion-ios-add"></i> Add New</a>
        </div>

    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <h4 class="card-title">Warping Machine Master</h4>
                    <p class="card-title-desc">
                        &nbsp;&nbsp;&nbsp;
                    </p>
                    <div class="table-responsive">
                        <table id="datatable" class="table table-stripedp" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(Model => Model.ID)</th>
                                    <th>@Html.DisplayNameFor(Model => Model.After)</th>
                                    <th>@Html.DisplayNameFor(Model => Model.Before)</th>
                                    <th>@Html.DisplayNameFor(Model => Model.Status)</th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @if (Model != null && Model.Any())
                                {
                                    @foreach (var product in Model)
                                    {
                                        <tr>
                                            <td>@product.ID</td>
                                            <td>@product.After</td>
                                            <td>@product.Before</td>
                                            @if (@product.Status == 1)
                                            {
                                                <td> <span class="badge bg-success">Active</span> </td>
                                            }
                                            else
                                            {
                                                <td> <span class="badge bg-danger">InActive</span> </td>
                                            }
                                            <td class="textcenter">
                                                <a class="btn btn-outline-success btn-sm edit" title="Edit" href="@Url.Action("CreateOrEdit", "WarpingMachine", new { ID = @product.ID })">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>

                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="5"><div>No details available</div></td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
        <!-- end col -->
    </div>
</div>